### PR TITLE
Fix #74: Update mjml to 4.6.2

### LINKED ISSUE #74: new mjml version 4.6.2 available
A new version of `mjml` is available `2.6.2` but `dependabot` doesn't seems to create the necessary PR :(

EDIT: `2.6.2` is out too

### PR DESCRIPTION
**Pull request by kumy**
Just ran `npm update mjml`, hope it's ok

### CODE REVIEW

**Comment by danihodovic** [comment]
Thanks. Can you update package.json too?

**Comment by kumy** [comment]
I'm not used to nodejs, is there a command for that, or it 's a manual edit?

**Comment by danihodovic** [comment]
Try:

```bash
npm install mjml@latest
```

Commit the changes

**Comment by kumy** [comment]
Commit updated

**Comment by danihodovic** [comment]
Thanks!

**Pull request merged**
